#:schema node_modules/wrangler/config-schema.json
name = "sinkr-app-manager"
main = ".worker-next/index.mjs"

compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

routes = [
  { pattern = "<your domain>", custom_domain = true }
]

[vars]
DEPLOYMENT_ENV="production"
DEPLOYMENT_URL="https://<your domain>"

[[d1_databases]]
binding = "DATABASE"
database_name = "<your database name>"
database_id = "<your database id>"