// Generated by Wrangler by running `wrangler types`

interface Env {
	COORDINATION_SECRET: string;
	SocketHandler: DurableObjectNamespace<import("./src/index").SocketHandler>;
	ObjectCoordinator: DurableObjectNamespace<import("./src/index").ObjectCoordinator>;
	DATABASE: D1Database;
}
