#:schema node_modules/wrangler/config-schema.json
name = "sinkr-deployment"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = [ "nodejs_compat" ]

routes = [
  { pattern = "<your domain>", custom_domain = true }
]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "SocketHandler"
class_name = "SocketHandler"

[[durable_objects.bindings]]
name = "ObjectCoordinator"
class_name = "ObjectCoordinator"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]

[[migrations]]
tag = "v2"
renamed_classes = [{ from = "$DurableObject", to = "SocketHandler" }]
new_sqlite_classes = ["ObjectCoordinator"]

[[d1_databases]]
binding = "DATABASE"
database_name = "<your database name>"
database_id = "<your database id>"