#:schema node_modules/wrangler/config-schema.json
name = "sinkr-deployment"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "$DurableObject"
class_name = "$DurableObject"

[[migrations]]
tag = "v1"
new_classes = ["$DurableObject"]

[[d1_databases]]
binding = "DATABASE"
database_name = "<your database name>"
database_id = "<your database id>"